# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimiry < Formula
  desc "Mimiry CLI - Command-line interface for the Mimiry platform"
  homepage "https://github.com/mimiry-com/mimiry-releases"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.0.0/mimiry_darwin_amd64.tar.gz"
      sha256 "01209392e6f467780c13786370e3f36f2faeb8a10c7874a1166c38529ab0bd6c"

      def install
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.0.0/mimiry_darwin_arm64.tar.gz"
      sha256 "8175fbcce13ea9f0a9e07aa26a06c01d3aca2f49f7702ed3ed24115105782c9b"

      def install
        bin.install "mimiry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.0.0/mimiry_linux_amd64.tar.gz"
      sha256 "17477984b3644161c2e5de2d62fa5be7ffdba0acf5bcd15ca71c6757f24eb619"
      def install
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.0.0/mimiry_linux_arm64.tar.gz"
      sha256 "9ecef2fd7f106caa2f34b8c8173f82da9abbe9b545ae51c1c2bac3dd392df424"
      def install
        bin.install "mimiry"
      end
    end
  end

  test do
    system "#{bin}/mimiry", "version"
  end
end
