# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimiry < Formula
  desc "Mimiry CLI - Command-line interface for the Mimiry platform"
  homepage "https://github.com/mimiry-com/mimiry-releases"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.1.0/mimiry_darwin_amd64.tar.gz"
      sha256 "f9b0d1d03e68a029feadeafcc81652ad468ed7bd6fa99e7f05181b3b5c4aef5d"

      define_method(:install) do
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.1.0/mimiry_darwin_arm64.tar.gz"
      sha256 "c88285fd3854832ab76dc50f39eb4779f8c15fbadc9b35acb621ef3fc04a66db"

      define_method(:install) do
        bin.install "mimiry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.1.0/mimiry_linux_amd64.tar.gz"
      sha256 "3062e9f233d3ebb54bded97bee1ccaf5dd97f5399e841a2ede294c3f9abbe659"
      define_method(:install) do
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v1.1.0/mimiry_linux_arm64.tar.gz"
      sha256 "3710cc59b754abcea5723a0266ca288afc7e76fb032ba2ebc459b61ef9ac1bc4"
      define_method(:install) do
        bin.install "mimiry"
      end
    end
  end

  test do
    system "#{bin}/mimiry", "version"
  end
end
