# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimiry < Formula
  desc "Mimiry CLI - Command-line interface for the Mimiry platform"
  homepage "https://github.com/mimiry-com/mimiry-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v0.1.0/mimiry_darwin_amd64.tar.gz"
      sha256 "0d0cdae5de2ae355403844bad510a1a2a7d7c39e32b5d26e1c24094d15cb3ff5"

      def install
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v0.1.0/mimiry_darwin_arm64.tar.gz"
      sha256 "480cd5afef11e7be5f6f25bb3d5b1296478cf0d7d5a402f86abab48b36d00f64"

      def install
        bin.install "mimiry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v0.1.0/mimiry_linux_amd64.tar.gz"
      sha256 "1cd0e818f4dcbe129522af63322c59eba386732d45cb8a1725bcf8ea800096ce"
      def install
        bin.install "mimiry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mimiry-com/mimiry-releases/releases/download/v0.1.0/mimiry_linux_arm64.tar.gz"
      sha256 "9af396cde8df1ece60199d77bd5eb0cd3620f45c1ef519c6e209f6dad61db88a"
      def install
        bin.install "mimiry"
      end
    end
  end

  test do
    system "#{bin}/mimiry", "version"
  end
end
